### PR TITLE
Add Python 3.6 to tox/Travis env list

### PR DESCRIPTION
**Pull request by rneilson**

### CODE REVIEW

**Comment by rneilson** [comment]
@kumar303 Oh, so a bunch of the doctests are failing, btw. Seems to be ones where variables haven't been assigned, or where truncated sample output is listed (which of course doesn't match the test's output). Should those be disabled?

**Comment by kumar303** [comment]
I don't see any failing doctests. The doctests are all there for a reason so we should only delete them when the docs need to change.

**Comment by kumar303** [comment]
Request a review from me when this is ready. I use this tab to do reviews: https://github.com/pulls/review-requested

**Comment by rneilson** [comment]
@kumar303 Can't request a review, not a contributor :[

Also, doctests are failing for me, locally. For example:
```
File "usage.rst", line 377, in usage
Failed example:
    sender.request_header
Expected:
    u'Hawk mac="...", id="some-sender", ts="...", nonce="..."'
Got:
    'Hawk mac="k5BkHt7uXnMalhb6CLVPWgPQ6p7XTaynYLy3CAyZP3k=", id="some-sender", ts="1491506647", nonce="TZfiak"'
```

**Comment by kumar303** [comment]
ok, I added you as a repo collaborator :)

> Also, doctests are failing for me, locally.

It's because of the unicode literal which only gets printed in Python 2. I think the [tox.ini](https://github.com/kumar303/mohawk/blob/master/tox.ini#L16) needs this:
````ini
[testenv:docs]
basepython=python2.7
changedir=docs
deps={[base]deps}
commands=
sphinx-build -b html -b doctest -d {envtmpdir}/doctrees . {envtmpdir}/html
````

**Comment by rneilson** [comment]
That seems to have worked for me, thanks.

**Comment by rneilson** [comment]
@kumar303 micropoke...

**Comment by rneilson** [comment]
@kumar303 Ah, no worries. Hope you had a good vacation.

**Pull request merged**
